// =========================================================
// Extended data — contracts, site updates, team, permissions
// =========================================================

// ---------- Contracts ----------
const CONTRACT_TYPES = [
  { value: "Purchase Agreement",      icon: "building" },
  { value: "JV / Partnership",        icon: "user" },
  { value: "Shareholders Agreement",  icon: "building" },
  { value: "Loan Agreement",          icon: "loans" },
  { value: "Employment",              icon: "user" },
  { value: "Lease",                   icon: "home" },
  { value: "Construction",            icon: "building" },
  { value: "SPV Agreement",           icon: "contract" },
  { value: "LOI",                     icon: "contract" },
  { value: "Insurance",               icon: "lock" },
  { value: "NDA",                     icon: "lock" },
  { value: "Service",                 icon: "settings" },
];

const STATUS_CHIP = {
  "Active":            "pos",
  "Pending signature": "warn",
  "Awaiting review":   "warn",
  "Expiring soon":     "warn",
  "Expired":           "neg",
  "Terminated":        "neg",
  "Draft":             "",
};

// Days until expiry helper
const daysUntil = (dateStr) => {
  if (!dateStr || !/^[A-Z]/.test(dateStr.split(" ")[0])) return null;
  const d = new Date(dateStr);
  if (isNaN(d.getTime())) return null;
  const now = new Date("May 24, 2026");
  return Math.round((d - now) / (1000 * 60 * 60 * 24));
};

const contracts = [
  {
    id: "ct-cantonments-spa",
    name: "Sale & Purchase Agreement — Cantonments Heights",
    type: "Purchase Agreement",
    parties: ["Kobby Ghanney", "Ridge Residences Ltd."],
    value: 320000, currency: "USD",
    linkedTo: { kind: "investment", id: "apt-cantonments", label: "Cantonments Heights — Unit 8B" },
    status: "Active",
    signedDate: "Sep 12, 2024",
    effectiveDate: "Sep 12, 2024",
    expiresDate: "Q1 2027 (handover)",
    fileName: "Cantonments_SPA_signed_v3.pdf",
    fileSize: "2.4 MB",
    pages: 38,
    uploadedBy: "Kobby",
    uploadedAt: "Sep 14, 2024",
    notes: "Signed and notarised. Title deed held by developer; transfers on handover.",
    attachments: 2,
  },
  {
    id: "ct-eastlegon-spa",
    name: "Sale & Purchase Agreement — East Legon Hills",
    type: "Purchase Agreement",
    parties: ["Kobby Ghanney", "Devtraco Plus"],
    value: 245000, currency: "USD",
    linkedTo: { kind: "investment", id: "apt-east-legon", label: "East Legon Hills — Unit 14C" },
    status: "Active",
    signedDate: "Nov 04, 2024",
    effectiveDate: "Nov 04, 2024",
    expiresDate: "Q3 2027 (handover)",
    fileName: "EastLegon_SPA_v2.pdf",
    fileSize: "1.9 MB",
    pages: 32,
    uploadedBy: "Kobby",
    uploadedAt: "Nov 06, 2024",
    notes: "Standard developer SPA. Payment schedule appendix attached.",
    attachments: 1,
  },
  {
    id: "ct-airport-spa",
    name: "Sale & Purchase Agreement — Airport Residential",
    type: "Purchase Agreement",
    parties: ["Kobby Ghanney", "Goldkey Properties"],
    value: 410000, currency: "USD",
    linkedTo: { kind: "investment", id: "apt-airport-res", label: "Airport Residential — Unit 22A" },
    status: "Active",
    signedDate: "Mar 22, 2024",
    effectiveDate: "Mar 22, 2024",
    expiresDate: "Q4 2026 (handover)",
    fileName: "AirportRes_SPA_executed.pdf",
    fileSize: "3.1 MB",
    pages: 41,
    uploadedBy: "Kwame Asante",
    uploadedAt: "Mar 25, 2024",
    notes: "Reviewed and signed off by counsel.",
    attachments: 3,
  },
  {
    id: "ct-bloom-spa",
    name: "Sale & Purchase Agreement — Bloom Tower JVC",
    type: "Purchase Agreement",
    parties: ["Kobby Ghanney", "Bloom Holding LLC"],
    value: 1450000, currency: "AED",
    linkedTo: { kind: "investment", id: "apt-dxb-jvc", label: "Bloom Tower JVC — Unit 1109" },
    status: "Active",
    signedDate: "Feb 14, 2025",
    effectiveDate: "Feb 14, 2025",
    expiresDate: "Q2 2027 (handover)",
    fileName: "BloomTower_SPA_AED.pdf",
    fileSize: "4.2 MB",
    pages: 56,
    uploadedBy: "Kwame Asante",
    uploadedAt: "Feb 18, 2025",
    notes: "Reviewed by Dubai counsel. Escrow account under RERA framework.",
    attachments: 4,
  },
  {
    id: "ct-sister-jv",
    name: "Joint Venture Agreement — Tema Block (6-Unit)",
    type: "JV / Partnership",
    parties: ["Kobby Ghanney", "Afia Ghanney (sister)"],
    value: 480000, currency: "USD",
    linkedTo: { kind: "investment", id: "apt-sister-block", label: "6-Unit Block — Tema Comm. 25" },
    status: "Active",
    signedDate: "Jan 20, 2026",
    effectiveDate: "Jan 20, 2026",
    expiresDate: "Indefinite",
    fileName: "Tema_Block_JV_Agreement.pdf",
    fileSize: "1.2 MB",
    pages: 18,
    uploadedBy: "Kwame Asante",
    uploadedAt: "Jan 22, 2026",
    notes: "50/50 equity split. Profit waterfall in Schedule 2. Exit triggers in Schedule 3.",
    attachments: 0,
  },
  {
    id: "ct-scoop-share",
    name: "Shareholders Agreement — Scoop & Co.",
    type: "Shareholders Agreement",
    parties: ["Kobby Ghanney", "Scoop & Co. Ltd.", "Maame Akoto (CEO)"],
    value: 45000, currency: "USD",
    linkedTo: { kind: "investment", id: "biz-icecream", label: "Scoop & Co. — Ice Cream Parlour" },
    status: "Active",
    signedDate: "Aug 03, 2025",
    effectiveDate: "Aug 03, 2025",
    expiresDate: "Indefinite",
    fileName: "ScoopCo_SHA_executed.pdf",
    fileSize: "0.8 MB",
    pages: 14,
    uploadedBy: "Kwame Asante",
    uploadedAt: "Aug 06, 2025",
    notes: "40% equity, board seat, monthly distribution rights.",
    attachments: 1,
  },
  {
    id: "ct-spv-road",
    name: "SPV Operating Agreement — Eastern Corridor",
    type: "SPV Agreement",
    parties: ["Kobby Ghanney", "Volta Roads SPV Ltd.", "3 co-investors"],
    value: 220000, currency: "USD",
    linkedTo: { kind: "investment", id: "spv-road", label: "Eastern Corridor Road — SPV" },
    status: "Active",
    signedDate: "Apr 11, 2025",
    effectiveDate: "Apr 11, 2025",
    expiresDate: "Completion of road project",
    fileName: "VoltaRoads_SPV_OpAgr_v4.pdf",
    fileSize: "2.7 MB",
    pages: 44,
    uploadedBy: "Kwame Asante",
    uploadedAt: "Apr 14, 2025",
    notes: "15% equity. Distributions on Ministry milestone payments.",
    attachments: 2,
  },
  {
    id: "ct-wewire-gh",
    name: "Employment Contract — WeWire Ghana",
    type: "Employment",
    parties: ["Kobby Ghanney", "WeWire Ghana Ltd."],
    value: 123250, currency: "GHS",
    linkedTo: { kind: "income", id: "sal-wewire-gh", label: "Salary — WeWire Ghana" },
    status: "Active",
    signedDate: "Jun 01, 2024",
    effectiveDate: "Jun 01, 2024",
    expiresDate: "Indefinite",
    fileName: "WeWire_GH_Employment.pdf",
    fileSize: "0.6 MB",
    pages: 12,
    uploadedBy: "Kobby",
    uploadedAt: "Jun 03, 2024",
    notes: "Director-level. Deferral clause exercised since Jul 2025.",
    attachments: 0,
  },
  {
    id: "ct-wewire-dxb",
    name: "Employment Contract — WeWire Dubai",
    type: "Employment",
    parties: ["Kobby Ghanney", "WeWire DMCC"],
    value: 44040, currency: "AED",
    linkedTo: { kind: "income", id: "sal-wewire-dxb", label: "Salary — WeWire Dubai" },
    status: "Active",
    signedDate: "Aug 10, 2024",
    effectiveDate: "Aug 10, 2024",
    expiresDate: "Indefinite",
    fileName: "WeWire_DMCC_Contract.pdf",
    fileSize: "0.7 MB",
    pages: 14,
    uploadedBy: "Kobby",
    uploadedAt: "Aug 12, 2024",
    notes: "DIFC contract framework. End-of-service gratuity per UAE law.",
    attachments: 1,
  },
  {
    id: "ct-loan-kontact",
    name: "Loan Agreement — Kontact Logistics Ltd.",
    type: "Loan Agreement",
    parties: ["Kobby Ghanney", "Kontact Logistics Ltd."],
    value: 45000, currency: "USD",
    linkedTo: { kind: "loan", id: "ln-kontact", label: "Kontact Logistics Loan" },
    status: "Active",
    signedDate: "Feb 04, 2026",
    effectiveDate: "Feb 04, 2026",
    expiresDate: "Feb 04, 2027",
    fileName: "Kontact_Loan_Agreement.pdf",
    fileSize: "0.5 MB",
    pages: 8,
    uploadedBy: "Kwame Asante",
    uploadedAt: "Feb 04, 2026",
    notes: "12% APR · Personal guarantee from CEO · Invoice assignment.",
    attachments: 2,
  },
  {
    id: "ct-loan-rosewood",
    name: "Secured Loan — Rosewood Properties",
    type: "Loan Agreement",
    parties: ["Kobby Ghanney", "Rosewood Properties Ltd."],
    value: 35000, currency: "USD",
    linkedTo: { kind: "loan", id: "ln-rosewood", label: "Rosewood Properties Loan" },
    status: "Active",
    signedDate: "Oct 03, 2025",
    effectiveDate: "Oct 03, 2025",
    expiresDate: "Oct 03, 2026",
    fileName: "Rosewood_SecuredLoan.pdf",
    fileSize: "0.6 MB",
    pages: 10,
    uploadedBy: "Kwame Asante",
    uploadedAt: "Oct 04, 2025",
    notes: "Secured against vehicle fleet. Quarterly repayment schedule.",
    attachments: 1,
  },
  {
    id: "ct-construction-tema",
    name: "Construction Contract — Tema Block Build",
    type: "Construction",
    parties: ["Sister JV", "Adansi Build Ltd."],
    value: 280000, currency: "USD",
    linkedTo: { kind: "investment", id: "apt-sister-block", label: "6-Unit Block — Tema Comm. 25" },
    status: "Active",
    signedDate: "Feb 03, 2026",
    effectiveDate: "Feb 10, 2026",
    expiresDate: "Q2 2027",
    fileName: "Tema_Construction_Contract.pdf",
    fileSize: "1.4 MB",
    pages: 22,
    uploadedBy: "Kwame Asante",
    uploadedAt: "Feb 05, 2026",
    notes: "Stage payments tied to milestones. 5% retention until handover.",
    attachments: 3,
  },
  {
    id: "ct-scoop-lease",
    name: "Commercial Lease — Scoop & Co. East Legon",
    type: "Lease",
    parties: ["Scoop & Co. Ltd.", "East Legon Properties"],
    value: 24000, currency: "USD",
    linkedTo: { kind: "investment", id: "biz-icecream", label: "Scoop & Co." },
    status: "Active",
    signedDate: "Jul 22, 2025",
    effectiveDate: "Aug 01, 2025",
    expiresDate: "Aug 01, 2028",
    fileName: "ScoopCo_Lease_3yr.pdf",
    fileSize: "0.4 MB",
    pages: 9,
    uploadedBy: "Maame Akoto",
    uploadedAt: "Jul 25, 2025",
    notes: "3-year lease, 8% annual escalation, renewal option.",
    attachments: 0,
  },
  {
    id: "ct-spintex-loi",
    name: "Letter of Intent — Spintex Location",
    type: "LOI",
    parties: ["Kobby Ghanney", "Spintex Lifestyle Mall"],
    value: 0, currency: "USD",
    linkedTo: { kind: "project", id: "pr-scoop2", label: "Scoop & Co. — Spintex location" },
    status: "Awaiting review",
    signedDate: null,
    effectiveDate: "—",
    expiresDate: "Jun 15, 2026",
    fileName: "Spintex_LOI_draft.pdf",
    fileSize: "0.2 MB",
    pages: 4,
    uploadedBy: "Kobby",
    uploadedAt: "May 18, 2026",
    notes: "Initial LOI from mall. Kwame reviewing terms — feedback due this week.",
    attachments: 0,
  },
  {
    id: "ct-akua-loan",
    name: "Loan Note — Akua Mensah",
    type: "Loan Agreement",
    parties: ["Kobby Ghanney", "Akua Mensah"],
    value: 18000, currency: "USD",
    linkedTo: { kind: "loan", id: "ln-akua", label: "Akua Mensah Loan" },
    status: "Active",
    signedDate: "Nov 12, 2025",
    effectiveDate: "Nov 12, 2025",
    expiresDate: "Aug 12, 2026",
    fileName: "Akua_LoanNote_signed.pdf",
    fileSize: "0.2 MB",
    pages: 3,
    uploadedBy: "Kobby",
    uploadedAt: "Nov 12, 2025",
    notes: "Simple promissory note, 8% APR. Monthly amortisation.",
    attachments: 0,
  },
  {
    id: "ct-insurance-bloom",
    name: "Off-Plan Insurance Policy — Bloom Tower",
    type: "Insurance",
    parties: ["Kobby Ghanney", "Oman Insurance Co."],
    value: 7200, currency: "AED",
    linkedTo: { kind: "investment", id: "apt-dxb-jvc", label: "Bloom Tower JVC" },
    status: "Expiring soon",
    signedDate: "Mar 01, 2025",
    effectiveDate: "Mar 01, 2025",
    expiresDate: "Jun 15, 2026",
    fileName: "BloomTower_OffPlanInsurance.pdf",
    fileSize: "0.3 MB",
    pages: 6,
    uploadedBy: "Kobby",
    uploadedAt: "Mar 02, 2025",
    notes: "Renewal quote requested — broker says rates flat.",
    attachments: 0,
  },
];

// ---------- Site updates (keyed by investment id) ----------
const siteUpdates = {
  "apt-cantonments": [
    { id: "su-cant-4", date: "Apr 18, 2026", milestone: "6th floor slab cast", progress: 0.64, reporter: "Site Engineer (Ridge Residences)", photos: 12, notes: "Slab on 6th floor poured and curing. Structural inspection scheduled next week. On schedule.", status: "verified" },
    { id: "su-cant-3", date: "Mar 02, 2026", milestone: "Block work — floors 1–5", progress: 0.50, reporter: "Site Engineer", photos: 8, notes: "Blockwork complete to 5th floor. Plaster started on lower units.", status: "verified" },
    { id: "su-cant-2", date: "Jan 15, 2026", milestone: "Substructure complete", progress: 0.32, reporter: "Site Engineer", photos: 14, notes: "All raft foundations cast. Columns to ground floor poured.", status: "verified" },
    { id: "su-cant-1", date: "Sep 28, 2025", milestone: "Ground breaking", progress: 0.05, reporter: "Developer", photos: 22, notes: "Site cleared, excavation begun. Boundary walls erected.", status: "verified" },
  ],
  "apt-east-legon": [
    { id: "su-el-3", date: "Apr 20, 2026", milestone: "6th floor slab", progress: 0.40, reporter: "Site Engineer (Devtraco)", photos: 9, notes: "6th floor slab cast. Lift core continuing up.", status: "verified" },
    { id: "su-el-2", date: "Feb 10, 2026", milestone: "Block work — lower floors", progress: 0.28, reporter: "Site Engineer", photos: 7, notes: "Blockwork up to floor 3.", status: "verified" },
    { id: "su-el-1", date: "Nov 18, 2025", milestone: "Foundation complete", progress: 0.10, reporter: "Developer", photos: 11, notes: "Foundation works finished. Columns going up.", status: "verified" },
  ],
  "apt-airport-res": [
    { id: "su-ar-3", date: "May 02, 2026", milestone: "Finishing — units 18-24", progress: 0.70, reporter: "Site Engineer (Goldkey)", photos: 16, notes: "Internal finishes started on upper units. Tiling and joinery in progress.", status: "verified" },
    { id: "su-ar-2", date: "Feb 28, 2026", milestone: "MEP rough-in", progress: 0.55, reporter: "MEP Contractor", photos: 12, notes: "Mechanical, electrical, plumbing roughed in floors 1–20.", status: "verified" },
    { id: "su-ar-1", date: "Oct 14, 2025", milestone: "Envelope closed", progress: 0.40, reporter: "Developer", photos: 19, notes: "Façade installation complete. Building watertight.", status: "verified" },
  ],
  "apt-dxb-jvc": [
    { id: "su-bt-2", date: "Apr 30, 2026", milestone: "10th floor structure", progress: 0.40, reporter: "Bloom Construction Lead", photos: 14, notes: "Structure climbing on schedule. Façade contractor mobilising next month.", status: "verified" },
    { id: "su-bt-1", date: "Jan 20, 2026", milestone: "20% milestone — substructure", progress: 0.20, reporter: "Bloom Holding", photos: 18, notes: "All substructure works complete. Tower crane installed.", status: "verified" },
  ],
  "apt-sister-block": [
    { id: "su-tb-2", date: "May 08, 2026", milestone: "Foundation cast", progress: 0.35, reporter: "Afia Ghanney (sister)", photos: 6, notes: "Strip foundations cast on all 6 units. Ready for block work next month.", status: "verified" },
    { id: "su-tb-1", date: "Feb 22, 2026", milestone: "Site cleared & excavation", progress: 0.12, reporter: "Afia Ghanney", photos: 8, notes: "Site cleared, foundations marked out and dug.", status: "verified" },
  ],
  "spv-road": [
    { id: "su-er-3", date: "May 14, 2026", milestone: "Milestone 3 invoice submitted", progress: 0.62, reporter: "SPV Operator", photos: 4, notes: "Invoice for GHS 18.4M submitted to Ministry of Roads. Expected release Jul 2026.", status: "verified" },
    { id: "su-er-2", date: "Mar 04, 2026", milestone: "Subbase & base course — 12km", progress: 0.50, reporter: "Site Director", photos: 22, notes: "Subbase laid on 12km. Base course progressing on first 8km.", status: "verified" },
    { id: "su-er-1", date: "Nov 30, 2025", milestone: "Earthworks complete on Phase 1", progress: 0.30, reporter: "Site Director", photos: 15, notes: "Phase 1 earthworks completed and accepted by client engineer.", status: "verified" },
  ],
};

// ---------- Team ----------
const ROLE_PRESETS = {
  "Owner":               { color: "var(--ink)",       desc: "Full access. Can do anything in the portal." },
  "Personal Assistant":  { color: "var(--positive)",  desc: "Day-to-day management. Records loans, payments, income, calendar." },
  "Lawyer":              { color: "var(--warn)",      desc: "Contracts and legal. View loans / projects, upload contracts." },
  "Accountant":          { color: "var(--accent)",    desc: "Read-only on financials. Can export statements and books." },
  "Read-only":           { color: "var(--muted)",     desc: "Dashboard view only. No edits anywhere." },
  "Custom":              { color: "var(--negative)",  desc: "Granular permissions per module." },
};

const MODULES = [
  { key: "overview",    label: "Overview" },
  { key: "income",      label: "Income" },
  { key: "investments", label: "Investments" },
  { key: "trading",     label: "Trading" },
  { key: "loans",       label: "Loans" },
  { key: "projects",    label: "Projects" },
  { key: "contracts",   label: "Contracts" },
  { key: "networth",    label: "Net Worth" },
];

// permission level per module: "none" | "view" | "edit" | "full"
const ROLE_PERMS = {
  "Owner": {
    overview: "full", income: "full", investments: "full", trading: "full",
    loans: "full", projects: "full", contracts: "full", networth: "full",
  },
  "Personal Assistant": {
    overview: "view", income: "edit", investments: "view", trading: "none",
    loans: "edit", projects: "edit", contracts: "view", networth: "view",
  },
  "Lawyer": {
    overview: "view", income: "none", investments: "view", trading: "none",
    loans: "view", projects: "view", contracts: "full", networth: "none",
  },
  "Accountant": {
    overview: "view", income: "view", investments: "view", trading: "view",
    loans: "view", projects: "view", contracts: "view", networth: "view",
  },
  "Read-only": {
    overview: "view", income: "none", investments: "none", trading: "none",
    loans: "none", projects: "none", contracts: "none", networth: "none",
  },
};

const team = [
  {
    id: "tm-kobby", name: "Kobby Ghanney", email: "kobby@ghanney.com",
    role: "Owner", initials: "KG", status: "Active",
    lastActive: "Now", twoFa: true, joined: "Jun 2024",
    location: "Accra / Dubai",
  },
  {
    id: "tm-ama", name: "Ama Owusu", email: "ama@ghanney.com",
    role: "Personal Assistant", initials: "AO", status: "Active",
    lastActive: "2 hours ago", twoFa: true, joined: "Sep 2024",
    location: "Accra",
  },
  {
    id: "tm-kwame", name: "Kwame Asante", email: "kwame@asantelaw.gh",
    role: "Lawyer", initials: "KA", status: "Active",
    lastActive: "Yesterday", twoFa: true, joined: "Nov 2024",
    location: "Accra",
    external: "Asante Law Group",
  },
  {
    id: "tm-naomi", name: "Naomi Tetteh", email: "naomi@ghanney.com",
    role: "Accountant", initials: "NT", status: "Active",
    lastActive: "3 days ago", twoFa: true, joined: "Oct 2024",
    location: "Accra",
  },
  {
    id: "tm-yusuf", name: "Yusuf Al-Hassan", email: "yusuf@dubaicapital.ae",
    role: "Accountant", initials: "YA", status: "Pending",
    lastActive: "—", twoFa: false, joined: "Invited 2 days ago",
    location: "Dubai",
    external: "Dubai Capital Partners",
  },
];

const teamActivity = [
  { t: "12 min ago",  who: "Ama Owusu",   msg: "Recorded loan repayment — Akua Mensah $2,000",       tag: "loan" },
  { t: "2 hours ago", who: "Ama Owusu",   msg: "Added calendar reminder: Bloom Tower payment Jul 1", tag: "calendar" },
  { t: "Yesterday",   who: "Kwame Asante",msg: "Uploaded contract draft — Spintex LOI",              tag: "contract" },
  { t: "Yesterday",   who: "Kwame Asante",msg: "Reviewed and commented on Tema Construction Contract", tag: "contract" },
  { t: "2 days ago",  who: "Naomi Tetteh",msg: "Exported April financial statements (PDF)",          tag: "export" },
  { t: "3 days ago",  who: "Ama Owusu",   msg: "Logged WeWire May commission accrual",               tag: "income" },
  { t: "5 days ago",  who: "Kobby Ghanney", msg: "Invited Yusuf Al-Hassan as Accountant (Dubai)",      tag: "team" },
];

Object.assign(window, {
  contracts, siteUpdates, team, teamActivity,
  ROLE_PRESETS, ROLE_PERMS, MODULES,
  CONTRACT_TYPES, STATUS_CHIP, daysUntil,
});
